### ISSUE TITLE
`ue4 setroot` fails if path has a trailing slash

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4cli#1]
```
(venv) PS> ue4 setroot 'C:\Games\Epic Games\UE_4.21\'
Using user-specified engine root: C:\Games\Epic Games\UE_4.21"
Warning: the specified directory does not appear to contain a valid version of the Unreal Engine.
```
but
```
(venv) PS> ue4 setroot 'C:\Games\Epic Games\UE_4.21'
Using user-specified engine root: C:\Games\Epic Games\UE_4.21
```

It picked up a trailing `"` due to the trailing backslash, which suggests a string-escaping error somewhere.

**Comment by adamrehn** [comment]
Thanks for pointing this out, there were a few instances of raw path concatenation (i.e. not using `os.path.join()`) still lurking in the codebase that had escaped my previous tidying efforts.

**Comment by MadaraPremawardhana** [comment]
Hi @adamrehn I am still getting this when trying to build precomputes for UE version 4.26 for the GDAL library when trying to use LandscapeGen plugin.
