### ISSUE TITLE
ThirdParty library enumeration fails if engine path includes a symlink

### ISSUE THREAD

**Issue by stefanbuettner** [adamrehn/ue4cli#10]
Hi there,

for me, the third party library enumeration and therefore `ue4 libs` result was empty, probably because my engine installation path contains a symlink.
The intermediate `ubt_output.json` contains canonicalized paths whereas the engine root used in the `UE4BuildInterrogator` was different because it included a symlink.
Therefore, the check for a third party plugin using the full engine path fails for every module.
Thus, I propose to only check if the path includes `Engine/Source/ThirdParty` which should be sufficient.

See PR #9.

Cheers,
Stefan

**Comment by adamrehn** [comment]
Hi Stefan, thanks for reporting this!

Given that the Engine root path is also used to transform relative paths in subsequent steps of the interrogation process, a more thorough alternative might simply be to resolve any symlinks in the Engine root path up front. This should ensure that all of the absolute paths reported by ue4cli share the same common prefix.

I've implemented this change in commit 840ac82. Could you please let me know if this fixes the issue for you?

**Comment by stefanbuettner** [comment]
This sounds indeed like a better solution.
Works for me.
Thanks :)
