### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by simonrenger** [adamrehn/ue4cli#16]
When I run `ue4 test --all` on my build server (Jenkins & Windows) I ran into this issue. It is the same on my local machine when I do it.
My SCM has control over the folder aka the folder is 'Read Only' (Perforce). Running ps as admin does not help either.

**Comment by adamrehn** [comment]
If the directory containing your Unreal project is read-only then presumably none of ue4cli's [descriptor commands](https://adamrehn.com/docs/ue4cli/descriptor-commands/) should function correctly. My suggestion would be to configure Perforce to allow write access to the directory and its contents, which I believe is controlled by the `allwrite` flag.

**Comment by simonrenger** [comment]
I will try to reproduce the scenario

**Comment by adamrehn** [comment]
I'm going to close this, since the underlying UE4 build tools that ue4cli invokes are designed to work with writeable project directories and avoiding the creation of read-only directories is a user concern that falls outside the scope of this project.
