### ISSUE TITLE
Run tests without -nullrhi

### ISSUE THREAD

**Issue by Skylonxe** [adamrehn/ue4cli#17]
Is there a way to run tests with rhi? I am asking because screenshot tests require that.

https://docs.unrealengine.com/en-US/Programming/Automation/ScreenShotComparison/index.html

For quick testing of screenshot test place Screenshot Function Test actor anywhere into level, save it and find the test in unrel frontend automation tab under Project category.

**Comment by adamrehn** [comment]
I've updated the [ue4 test](https://adamrehn.com/docs/ue4cli/descriptor-commands/test) command in ue4cli version 0.0.45 and added a flag called `--withrhi`, which will prevent ue4cli from injecting the `-nullrhi` when it runs the automation tests. Bear in mind that this will require GPU acceleration to function, so it won't work in containers or virtual machines that do not have GPU access.
