### ISSUE TITLE
Unable to pass platform in command line

### ISSUE THREAD

**Issue by kanekotic** [adamrehn/ue4cli#19]
Hello @adamrehn. When  trying to add platform to the cli command i get:
```bash
ue4 package -platform=android  
Error: invalid build configuration "-platform=android"
```
Not sure if i am currently doing something wrong. I also triend with `-platform=Linux` and `-platform=Mac` with same result. Thank in advance for any help you can provide.

**Comment by adamrehn** [comment]
Please read the relevant documentation prior to opening issues: https://adamrehn.com/docs/ue4cli/descriptor-commands/package

The syntax of your command is incorrect. You've specified additional arguments for UBT (in this case the `-platform` argument) without specifying a build configuration. As stated in the docs, the correct syntax is `ue4 package [CONFIGURATION] [EXTRA UAT ARGS]`, so your command should look like this:

```bash
# Package in Shipping configuration, passing the argument -platform=Android to UBT
ue4 package Shipping -platform=Android
```

**Comment by kanekotic** [comment]
thanks @adamrehn, thanks for the answer i did read it before. What does confuse from that documentation is that configuration is an optional parameter. From your example I feel it makes sense to add that this parameter is mandatory if any other UAT parameter is defined.

**Comment by adamrehn** [comment]
@kanekotic thanks for the feedback. That particular behaviour is fairly common for optional positional arguments in both command-line interfaces and programming language APIs, whereby options can only be omitted from right-to-left and specifying an optional positional argument requires that all positional arguments to its left must be specified. That being said, your experience is proof that this can be a source of confusion for users who are unfamiliar with that existing convention, so I've done as you suggested and updated the [documentation for the package command](https://adamrehn.com/docs/ue4cli/descriptor-commands/package) to explicitly state that a build configuration must be specified if passing additional arguments to UAT. Hopefully this will help avoid confusion for other users encountering this behaviour in the future.

**Comment by kanekotic** [comment]
thanks a lot for the effort and the change. and sorry i was not aware of that convention :)
