### ISSUE TITLE
Packaging with UE 4.22.0 full fails

### ISSUE THREAD

**Issue by deonblaauw** [adamrehn/ue4cli#2]
First of all, thanks for doing all this great work!

My project builds perfectly fine when using ue4 build, however when executing ue4 package, I get the following error. I'm not really sure what I'm doing wrong, but I'm pretty sure the mistake is on my side. My project is able to build using the UE4Editor GUI, am I missing a setting somewhere, or am I using the ue4 package command incorrectly perhaps? I'm using `adamrehn/ue4-full:4.22.0`

```
ue4@e3c157e0c282:~/Github$ ue4 package
Using user-specified engine root: /home/ue4/UnrealEngine

Running AutomationTool...

Fixing inconsistent case in filenames.
Setting up Mono
AutomationTool exists: Deleting
Compiling AutomationTool with xbuild
xbuild Source/Programs/AutomationTool/AutomationTool.csproj /p:Configuration=Development /p:Platform=AnyCPU /verbosity:quiet /nologo /p:TargetFrameworkProfile=
/home/ue4/UnrealEngine/Engine/Binaries/ThirdParty/Mono/Linux/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Referenced Project ../IOS/MobileDeviceInterface/MobileDeviceInterface.csproj not found, ignoring.
Compilation Succeeded
Start UAT: mono AutomationTool.exe BuildCookRun -utf8output -clientconfig=Shipping -serverconfig=Shipping -project=/home/ue4/Github/swarm_cpp.uproject -noP4 -cook -allmaps -build -stage -prereqs -pak -archive -archivedirectory=/home/ue4/Github/dist -platform=Linux -nodebuginfo
Parsing command line: BuildCookRun -utf8output -clientconfig=Shipping -serverconfig=Shipping -project=/home/ue4/Github/swarm_cpp.uproject -noP4 -cook -allmaps -build -stage -prereqs -pak -archive -archivedirectory=/home/ue4/Github/dist -platform=Linux -nodebuginfo -compile
WARNING: Ignoring -Compile argument because engine is installed.
ERROR: Scripts folder /home/ue4/UnrealEngine/Engine/Binaries/DotNET/AutomationScripts does not exist!
ERROR: AutomationScripts.Automation.dll was not found or could not be loaded, can't run scripts.
       (see /home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt for full exception trace)
AutomationTool exiting with ExitCode=1 (Error_Unknown)
RunUAT ERROR: AutomationTool was unable to run successfully.
Traceback (most recent call last):
  File "/usr/local/bin/ue4", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/cli.py", line 216, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/cli.py", line 88, in <lambda>
    'action': lambda m, args: m.packageDescriptor(os.getcwd(), args),
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/UnrealManagerBase.py", line 423, in packageDescriptor
    self.packageProject(dir, args[0] if len(args) > 0 else 'Shipping', args[1:])
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/UnrealManagerBase.py", line 398, in packageProject
    ] + extraArgs)
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/UnrealManagerBase.py", line 353, in runUAT
    Utility.run([self.getRunUATScript()] + args, cwd=self.getEngineRoot(), raiseOnError=True)
  File "/usr/local/lib/python3.6/dist-packages/ue4cli/Utility.py", line 138, in run
    raise Exception('child process ' + str(command) + ' failed with exit code ' + str(returncode))
Exception: child process ['/home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh', 'BuildCookRun', '-utf8output', '-clientconfig=Shipping', '-serverconfig=Shipping', '-project=/home/ue4/Github/swarm_cpp.uproject', '-noP4', '-cook', '-allmaps', '-build', '-stage', '-prereqs', '-pak', '-archive', '-archivedirectory=/home/ue4/Github/dist', '-platform=Linux', '-nodebuginfo'] failed with exit code 1
```

**Comment by adamrehn** [comment]
Thanks for reporting this! That output actually suggests that it might be a problem with ue4-docker rather than ue4cli. I'll have a look into it and let you know what I find.

**Comment by deonblaauw** [comment]
No, thank you. Please let me know where I can help, I can provide whatever output logs you wish. Like I mentioned, the project seems to build perfectly fine. I am using some plugins as well. What I can do, is to check what happens when I create one of the default (simple) projects in Unreal, just to provide us with more data-points to work with. I'll let you know as soon as I've done that.

**Comment by adamrehn** [comment]
@deonblaauw if you want to quickly test whether the `ue4-full` image is broken, you can package one of the Unreal Engine's bundled template projects:

```bash
cd /home/ue4/UnrealEngine/Templates/TP_FirstPerson
ue4 package
```

I just tested that command in the `ue4-full` image for 4.22.1 and can confirm that it worked, so if you can try it out in the 4.22.0 build and let me know whether that works that'd be extremely helpful.

**Comment by deonblaauw** [comment]
@adamrehn  Cool! I'll do that - I can do it tonight, will report back!

**Comment by adamrehn** [comment]
I've just built the `ue4-full` image for 4.22.0 and was able to successfully reproduce the error message from your initial comment. Looking at the [release notes for 4.22.1](https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1612034-4-22-1-hotfix-released), it looks like this is actually a bug in 4.22.0:

> Fixed! UE-71586 Unable to compile code projects from installed build on Linux

Unfortunately there's nothing that can be done in ue4cli to fix this, so the only solution is to upgrade to 4.22.1.

**Comment by deonblaauw** [comment]
@adamrehn Ok, great - thanks man! I'll use 4.22.1 instead then. I had an error when using ue4 build with 4.22.1, but I think it might have been on my side (hard drive was getting full). Let me dig into that!

**Comment by deonblaauw** [comment]
@adamrehn In can confirm that 4.22.1 works!
