### ISSUE TITLE
[Feature Request] Configurable target directory for packaged artifacts

### ISSUE THREAD

**Issue by patrickShaikh** [adamrehn/ue4cli#33]
Hey,

for my Jenkins pipeline its crucuial that I can configure the outpuut directory of

#ue4 package

My Jenkins slaves are ephemeral and running in docker, therefore I'm sharing the workspace between all of these slave-containers.
Since one of my pipelinesteps consists of parallel stages and each stage executes the package-command for a different platform I would like to configure thhe output-directory.

e.g.

pipeline {
	agent none

	stages {	
		//...

		stage("Package") {
			parallel {				
				stage("Package: Win64-Client") {
					agent {
						label 'ue4-windows' 
					}

					steps {
						sh 'ue4 package Shipping -platform=Win64'
						sh 'zip -r win64_client.zip dist'
						archiveArtifacts (
							artifacts: 'win64_client.zip',
							onlyIfSuccessful: true
						)
					}
				}

				stage("Package: Linux-Client") {
					agent {
						label 'ue4-linux' 
					}

					steps {
						sh 'ue4 package Shipping -platform=Linux'
						sh 'zip -r linux_client.zip dist'
						archiveArtifacts (
							artifacts: 'linux_client.zip',
							onlyIfSuccessful: true
						)
					}
				}
				
				//...
			}
		}
		
		//...
	}
	
	//...
}

As you can see its packaging for windows and linux and then creates a .zip for each. Since these steps are in parallel and the workspace is shared it zips me different files depending on speed of the package-process.
However this could be dodged by making the output-directory configurable.

I would like to be able to execute 

ue4 package Shipping -platform=Linux  -archivedirectory=linux_client
ue4 package Shipping -platform=Win64 -archivedirectory=win64_client

without it 'just' appending the string to the actually executed command but rather replacing:

Start UAT: mono AutomationTool.exe BuildCookRun -utf8output -clientconfig=Shipping -serverconfig=Shipping -project=/home/ue4/workspace/Game/Game.uproject -noP4 -cook -build -stage -prereqs -pak -archive -archivedirectory=/home/ue4/workspace/Game/dist -archivedirectory=./linux_client -platform=Linux -nodebuginfo -allmaps

Parsing command line: BuildCookRun -utf8output -clientconfig=Shipping -serverconfig=Shipping -project=/home/ue4/workspace/Game/Game.uproject -noP4 -cook -build -stage -prereqs -pak -archive -archivedirectory=/home/ue4/workspace/Game/dist -archivedirectory=./linux_client -platform=Linux -nodebuginfo -allmaps

In the code I've found the position where you're hardcoding the directory-name 'dist':

![grafik](https://user-images.githubusercontent.com/40237073/110255641-0e32d880-7f95-11eb-91c4-3452c16917cd.png)

I could also imagine this could be useful when it comes to multibranch pipelines.

**Comment by adamrehn** [comment]
Thanks for the suggestion, I've now altered the logic to only inject the default `-archivedirectory=` flag if the user has not specified one. This should provide the desired behaviour.
