### ISSUE TITLE
ue4 clean deletes third party binaries

### ISSUE THREAD

**Issue by arisona** [adamrehn/ue4cli#38]
ue4 clean deletes third party libraries that are not built from source. Not sure how this could be filtered.

Workaround for us is to use ue4 build -clean instead.

**Comment by adamrehn** [comment]
The clean command only removes the `Binaries` and `Intermediate` directories, so I'm guessing that you're storing your third-party libraries under `Binaries`? It's recommended that you store the original versions of these elsewhere in your source tree and instruct UBT to copy them to the `Binaries` directory at build time: https://docs.unrealengine.com/4.26/en-US/ProductionPipelines/BuildTools/UnrealBuildTool/ThirdPartyLibraries/#runtimedependencies

**Comment by arisona** [comment]
Thanks, makes sense. Will notify the plugin authors to fix this.
