### ISSUE TITLE
Request: A global flag that causes any command string(s) to be logged as they are executed

### ISSUE THREAD

**Issue by benpeck-eepics** [adamrehn/ue4cli#42]
It would be a useful feature for debugging and learning about the UE4 command line feature set if ue4-cli printed out any command strings to the logger as they are being performed, so that they can be inspected by the user. Something like a global verbose or show-cmds flag would be nice.

Thank you, have a nice day.

**Comment by adamrehn** [comment]
This behaviour is already available today, and is enabled by setting the `UE4CLI_VERBOSE` environment variable to a non-empty value, as documented here: https://docs.adamrehn.com/ue4cli/overview/environment-variables
