### ISSUE TITLE
`ue4 version` - print only the version

### ISSUE THREAD

**Issue by vaind** [adamrehn/ue4cli#51]
The `version` command prints additional info. Ideally, it should only print the version to be (more easily) usable in other command line tools. 

Current behavior:
```
$ ue4 version full 
Using user-specified engine root: C:\Program Files\Epic Games\UE_5.0
5.0.3
```

Expected behavior:
```
$ ue4 version full
5.0.3
```

**Comment by sleeptightAnsiC** [comment]
This exact use-case is actually working as expected right now, and would not mess with stdout of parent app.
Messages like this one are being printed to stderr, not stdout.

Though, the fact that such message cannot be suppressed is really (really) annoying.
The easiest way to fix it is probably by wrapping all messages with a function and by introducing a flag to toggle them.

https://github.com/adamrehn/ue4cli/blob/39d6f6ab2aab1484d104850f2de8f8f8f3cf45cf/ue4cli/UnrealManagerBase.py#L611-L620
https://github.com/adamrehn/ue4cli/blob/39d6f6ab2aab1484d104850f2de8f8f8f3cf45cf/ue4cli/Utility.py#L18-L23
