### ISSUE TITLE
Package linux dedicated server

### ISSUE THREAD

**Issue by boskiv** [adamrehn/ue4cli#7]
How to build and package a linux dedicated server with ue4?
Is there some argument to `ue4 package` command or I need to construct all with `ue4 uat`?

I have prepared a docker container with `ue4-docker` with Linux engine compiled inside. And run command `ue4` inside it.

**Comment by adamrehn** [comment]
The [ue4 package](https://adamrehn.com/docs/ue4cli/descriptor-commands/package) command allows you to specify additional arguments to UAT, so you can simply add the appropriate flags at the end of the command:

```bash
ue4 package Shipping -server -noclient
```

Starting in ue4cli version 0.0.33, the `-serverplatform=<PLATFORM>` argument will be automatically generated for you. In older versions of ue4cli you will need to specify this yourself.

It's worth noting that Installed Builds of the Unreal Engine do not currently include support for dedicated server targets by default, so you will not be able to use an unmodified version of the [ue4-minimal](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-minimal) or [ue4-full](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-full) container images to package a dedicated server. You will either need to add ue4cli to an image based on the [ue4-engine](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-engine) image or modify the BuildGraph XML data to include server target support in the Installed Build produced by the ue4-minimal image.
