### ISSUE TITLE
`ue4 test` fails calling `self.buildProject`

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4cli#8]
It looks like e7f878c31aae074a024e7f6cdfe64801a64b495e renamed `UnrealManagerBase.buildProject` to `UnrealManagerBase.buildDescriptor`, but `UnrealManagerBase.automationTests` still tries to call the former name.

This breaks `ue4 test`.

**Comment by adamrehn** [comment]
Thanks for catching this! One of these days I'll finally get around to implementing unit tests for ue4cli that can be run inside the `ue4-full` container image from ue4-docker, which will hopefully help catch oversights like this one.
